[build]
  command = "npm install && npm run build"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--build-from-source"
  NPM_VERBOSE = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
