[build]
  command = "npm install -g npm@latest && npm install && npm run build"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"  # Uses the latest 18.x LTS version
  NPM_FLAGS = "--build-from-source"
  NPM_VERBOSE = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas"]
  node_bridge = true

[dev]
  command = "npm start"
  targetPort = 3000
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
