[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_FLAGS = "--build-from-source"
  NPM_VERBOSE = "true"
  NPM_CONFIG_PREFIX = "/opt/buildhome/.npm-global"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
