[build]
  command = "npm ci --no-optional --loglevel verbose && npm run build"
  publish = "public"
  functions = "netlify/functions-dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional --build-from-source"
  NPM_VERBOSE = "true"
  NODE_ENV = "production"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas"]
  included_files = [
    "migrations/**",
    "src/utils/logger-wrapper.js",
    "src/utils/logger.js",
    "src/utils/logger.d.ts"
  ]  # Include required files in the function bundle

  # Configure the run-migrations function
  [functions.run-migrations]
    node_bundler = "esbuild"
    included_files = ["migrations/**"]
    # Add any specific environment variables needed for migrations
    environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Admin route
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Protected API routes

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
