[build]
  command = "npm install --loglevel verbose && npm run build"
  publish = "public"
  functions = "netlify/functions-dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--build-from-source"
  NPM_VERBOSE = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas"]
  included_files = ["migrations/**"]  # Include migrations in the function bundle

  # Configure the run-migrations function
  [functions.run-migrations]
    node_bundler = "esbuild"
    included_files = ["migrations/**"]
    # Add any specific environment variables needed for migrations
    environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Admin route
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Protected API routes

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
